# Generated by Django 5.0.2 on 2024-03-05 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatagory',
            fields=[
                ('product_catagory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_catagory_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_brand', models.CharField(max_length=100)),
                ('product_catagory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcatagory')),
            ],
        ),
    ]
